baseURL = "/"
languageCode = "es-es"
title = "magga"
# theme = "Docdock"
theme = "hugo-theme-docdock"
themesdir = "/themes"
ordersectionsby = "title"
[params]
themeStyle = "original"
themeVariant = "gold"
