baseURL = ""
languageCode = "es-es"
DefaultContentLanguage = "es"
ordersectionsby = "title"
theme = "docdock"
title = "magga"
enableGitInfo = true
# googleAnalytics = "UA-133551776-1"
[params]
themeStyle = "flex"
disableHomeIcon = false
disableSearch = true
[outputs]
home = [ "HTML", "RSS", "JSON"]
