baseURL = ""
languageCode = "es-es"
DefaultContentLanguage = "es"
ordersectionsby = "title"
theme = "docdock"
title = "magga"
enableGitInfo = true
googleAnalytics = "UA-123-45"
[params]
disableHomeIcon = true
disableSearch = true
themeStyle = "flex"
# themeVariant = "gold"
