baseURL = ""
languageCode = "es-es"
DefaultContentLanguage = "es"
ordersectionsby = "title"
theme = "docdock"
title = "magga"
enableGitInfo = true
[params]
themeStyle = "flex"
# themeVariant = "gold"
